### ISSUE TITLE
Dep optimization failed with error:

### ISSUE THREAD

**Issue by mesqueeb** [visualfanatic/vite-plugin-svg#3]
I have this error
```
[vite] Dep optimization failed with error:
path.endsWith is not a function
TypeError: path.endsWith is not a function
    at Object.test (/Users/lucaban/ghq/github.com/CyCraft/pepicons/pepicons.com/node_modules/vite-plugin-svg/index.js:41:30)
    at Object.transform (/Users/lucaban/ghq/github.com/CyCraft/pepicons/pepicons.com/node_modules/vite/dist/transform.js:94:23)
    at /Users/lucaban/ghq/github.com/CyCraft/pepicons/pepicons.com/node_modules/rollup/dist/shared/rollup.js:18200:25 {
  code: 'PLUGIN_ERROR',
  plugin: 'vite:transforms',
  hook: 'transform',
  id: '/Users/lucaban/ghq/github.com/CyCraft/pepicons/pepicons.com/node_modules/vue/dist/vue.runtime.esm-bundler.js',
  watchFiles: [
    '/Users/lucaban/ghq/github.com/CyCraft/pepicons/pepicons.com/node_modules/vue/dist/vue.runtime.esm-bundler.js'
  ]
}
```

This only happens with `1.0.0-beta.4`, not with `0.20.8`

**Comment by mesqueeb** [comment]
Closed in favour of #4
