### ISSUE TITLE
Works in dev build but VueComponent export is missing in production build, causing build failure

### ISSUE THREAD

**Issue by RegisFrey** [visualfanatic/vite-plugin-svg#7]
## Reproduction
- Start a new project (`yarn create vite-app`)
- Follow the directions in the vite-plugin-svg readme:
    - Add the SVG plugin in `vite.config.ts`
    - Import within a Vue component using the VueComponent export
- Run `yarn dev` and see the SVG + "hello world" text visible at localhost:3000
- Attempt to run `yarn build` (production build with rollup) but it errors on the SVG import.

```
vite-svg-error [master] $  yarn build
yarn run v1.22.4
$ vite build
vite v1.0.0-rc.4
⠸ Building for production...
[vite] Build errored out.
Error: 'VueComponent' is not exported by src/assets/example.svg, imported by src/components/HelloWorld.vue?vue&type=script&lang.js
    at error (/Users/regisfrey/Dev/vite-svg-error/node_modules/rollup/dist/shared/rollup.js:5206:30)
    at Module.error (/Users/regisfrey/Dev/vite-svg-error/node_modules/rollup/dist/shared/rollup.js:9687:16)
    at handleMissingExport (/Users/regisfrey/Dev/vite-svg-error/node_modules/rollup/dist/shared/rollup.js:9609:28)
    at Module.traceVariable (/Users/regisfrey/Dev/vite-svg-error/node_modules/rollup/dist/shared/rollup.js:10082:24)
    at ModuleScope.findVariable (/Users/regisfrey/Dev/vite-svg-error/node_modules/rollup/dist/shared/rollup.js:8631:39)
    at Identifier$1.bind (/Users/regisfrey/Dev/vite-svg-error/node_modules/rollup/dist/shared/rollup.js:4119:40)
    at Property$1.bind (/Users/regisfrey/Dev/vite-svg-error/node_modules/rollup/dist/shared/rollup.js:2847:23)
    at Property$1.bind (/Users/regisfrey/Dev/vite-svg-error/node_modules/rollup/dist/shared/rollup.js:8245:15)
    at ObjectExpression.bind (/Users/regisfrey/Dev/vite-svg-error/node_modules/rollup/dist/shared/rollup.js:2843:31)
    at ObjectExpression.bind (/Users/regisfrey/Dev/vite-svg-error/node_modules/rollup/dist/shared/rollup.js:7936:15) {
  code: 'MISSING_EXPORT',
  url: 'https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module',
  id: '/Users/regisfrey/Dev/vite-svg-error/src/components/HelloWorld.vue?vue&type=script&lang.js',
  pos: 10,
  loc: {
    file: '/Users/regisfrey/Dev/vite-svg-error/src/components/HelloWorld.vue?vue&type=script&lang.js',
    line: 2,
    column: 9
  },
  frame: '1: \n' +
    "2: import { VueComponent as ExampleSvg } from '../assets/example.svg';\n" +
    '            ^\n' +
    '3: \n' +
    '4: export default {',
  watchFiles: [
    '/Users/regisfrey/Dev/vite-svg-error/index.html',
    '/Users/regisfrey/Dev/vite-svg-error/src/main.js',
    '/Users/regisfrey/Dev/vite-svg-error/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js',
    '/Users/regisfrey/Dev/vite-svg-error/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js',
    '/Users/regisfrey/Dev/vite-svg-error/node_modules/@vue/shared/dist/shared.esm-bundler.js',
    '/Users/regisfrey/Dev/vite-svg-error/node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js',
    '/Users/regisfrey/Dev/vite-svg-error/src/App.vue',
    '/Users/regisfrey/Dev/vite-svg-error/src/index.css',
    '/Users/regisfrey/Dev/vite-svg-error/src/App.vue?vue&type=script&lang.js',
    '/Users/regisfrey/Dev/vite-svg-error/src/App.vue?vue&type=template&id=7ba5bd90',
    '/Users/regisfrey/Dev/vite-svg-error/src/components/HelloWorld.vue',
    '/Users/regisfrey/Dev/vite-svg-error/src/components/HelloWorld.vue?vue&type=script&lang.js',
    '/Users/regisfrey/Dev/vite-svg-error/src/components/HelloWorld.vue?vue&type=template&id=469af010',
    '/Users/regisfrey/Dev/vite-svg-error/src/assets/example.svg'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by visualfanatic** [comment]
@RegisFrey I just released `vite-plugin-svg@0.7.0` and the issue should be gone, I also tested it on your reproduction repo (thanks for it by the way!) and it works. Thank you for reporting the issue, I was totally unaware of it even though I monitor closely the commits inside the Vite repo 😞 As it turns out `process.env.NODE_ENV` is no longer set to `production` when `vite build` is run, fortunately sometime ago API for transforms was slightly changed and `isBuild` is provided to both `test` and `transform`. Let me know if the issue is also gone on your side.

**Comment by RegisFrey** [comment]
Yes, looks like it builds with rc 4 and the updated vite-plugin-svg@0.7.0. Thank you.

**Comment by ramoneg** [comment]
Referencing it as a js property worked for me:
`<img :src="'/images/cart.svg'">`

**Comment by wsz7777** [comment]
![image](https://user-images.githubusercontent.com/33828341/123030038-b2da0880-d414-11eb-8bbb-114d013ae5d9.png)

![image](https://user-images.githubusercontent.com/33828341/123029987-9c33b180-d414-11eb-897a-5a9b612f3935.png)

I have a case

**Comment by wsz7777** [comment]
![image](https://user-images.githubusercontent.com/33828341/123030152-e2891080-d414-11eb-8a11-654c7fc4afc8.png)

how to override this declare definition ?
